//================================================================================
// Peer Model Tool Chain
// Copyright (C) 2021 Eva Maria Kuehn
//--------------------------------------------------------------------------------
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//================================================================================
//SYSTEM:    Practical Peer Model Toolchain "for the poor woman/man"
//AUTHOR:    Eva Maria Kuehn
//CREATED:   January 2021 
//================================================================================

package codeGen.PmDsl;

import qa.exceptions.SNHException;

//================================================================================
// automatically generate code
// - nb: most parts are fixed
// - in some parts my use case name needs to be inserted (all marked with "<<<<<<")
public class PmDslFixGoCode {	
	//--------------------------------------------------------------------------------
	// for writing code to respective file
	PmDslCodeWriter codeWriter;

	//================================================================================
	// CONSTRUCTORS
	//================================================================================
	//--------------------------------------------------------------------------------
	// goUseCaseDirFileName ... the directory name under "src" in go automaton, where the compiled use cases are generated in
	public PmDslFixGoCode(PmDslCodeWriter codeWriter) {
		this.codeWriter = codeWriter;
	}

	//================================================================================
	// USE CASE FILE PARTS
	//================================================================================
	//--------------------------------------------------------------------------------
	public void generateUseCaseHeader() throws SNHException {
		//--------------------------------------------------------------------------------
		// switch file
		codeWriter.switch2File(PmDslDefs.DSL_XML_FILE_ID);
		//--------------------------------------------------------------------------------
		// write xml header
		// - TBD: version number
		codeWriter.writelnInd("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\" ?>");
		//--------------------------------------------------------------------------------
		// write header that it is an auto gen file
		writeAutoFileHeader(PmDslDefs.DSL_XML_FILE_ID);
	}

	//================================================================================
	// FILE HEADER & TAIL
	//================================================================================
	//--------------------------------------------------------------------------------
	// write header info that this code is autogenerated
	public void writeAutoFileHeader(int fileId) throws SNHException {
		codeWriter.writeln("<!-- AUTO GENERATED FILE -->");
	}
	//--------------------------------------------------------------------------------
	// write header info that this code is autogenerated
	public void writeAutoFileTail() throws SNHException {
		codeWriter.writeln("!-- END OF FILE -->");
	}


}


//================================================================================
// EOF
//================================================================================
